workflows:
    Yerenzter:
        name: 'Yerenzter'
        environment:
            java: 1.8
            vars:
                PACKAGE_NAME: "qubonic.onec"
        scripts: |
            name: "1C"
            echo cat 'app/build/bin/signed.apk'
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: '*'
                - include: true
                - source: true
            cancel_previous_builds: false
        artifacts:
            - build/bin/signed.apk
        publishing:
            email:
                recipients:
                    - yerenzter@yandex.com
        scripts:
            - echo 'Build success!'
