workflows:
    Yerenzter:
        name: 'Yerenzter'
        environment:
            java: 1.8
        artifacts:
            - 'https://github.com/Yerenzter/onec-app/raw/main/app/build/bin/signed.apk'
