workflows:
    android-app:
        name: Native Android
        environment:
            java: 1.8
            vars:
                PACKAGE_NAME: "qubonic.onec"
        scripts:
            ./gradlew test
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: '*'
                - include: true
                - source: true
            cancel_previous_builds: false
        artifacts:
            - app/build/**/outputs/**/**/*.apk
        scripts:
            ./gradlew test
        publishing:
            email:
                recipients:
                    - yerenzter@yandex.com
        scripts:
            - echo 'Build success!'
