workflows:
    Yerenzter:
        name: 'Yerenzter'
        environment:
            android_signing:
                - keystore_reference
            java: 1.8
            vars:
                PACKAGE_NAME: "qubonic.onec"
        scripts: |
            name: "1C"
            echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: '*'
                - include: true
                - source: true
            cancel_previous_builds: false
        artifacts:
            - build/bin/signed.apk
        publishing:
            email:
                recipients:
                    - yerenzter@yandex.com
        scripts:
            - echo 'Build success!'
