workflows:
    Yerenzter:
        name: 'Yerenzter'
        environment:
            java: 1.8
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: '*'
                - include: true
                - source: true
            cancel_previous_builds: false
        artifacts:
            - build/bin/signed.apk
        publishing:
            email:
                recipients:
                    - yerenzter@yandex.com
        scripts:
            - echo 'Build success!'
            jarsigner 
            -verbose
            -verify
            -cert
            -$FC_BUILD_OUTPUT/.*apk
